# Site settings
title: pilarblazquez.me
email: obeces@gmail.com
description: "Página personal de Pilar Blázquez"
url: "https://pilarblazquez.me" # the base hostname & protocol for your site, e.g. http://example.com
future: true

name: pilarblazquez.me
base-url: ""

#environment: production
#newsletter_endpoint: 'https://prueba4.free.beeceptor.com/my/api/path'

## Tracker
google_id: UA-156454891-1

## Social
linkedin: "https://www.linkedin.com/pilarblazquez"
twitter: "https://www.twitter.com/praxagora21"

# keywords: ''

# Site permalink settings:
permalink: /:title/
# End

# Date format settings
date_format: "%B %-d, %Y"
# End

# Sass
sass:
    style: compressed
# End

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Plugins configuration (in same order)

# Descomentar línea url para permitir que el plugin sitemap genere automáticamente el archivo robots.txt si no existe
# Aunque no permite añadir más contenido al robots.txt
# Sitemap
# url: "https://pilarblazquez.me" # the base hostname & protocol for your site
# End

defaults:
    -
     scope:
         path: ""
     values:
         author: "Pilar Blázquez"
         layout: base
         lang: es
         base-url: "/"
         origin_url: "https://pilarblazquez.me"

exclude: ['package.json', 'node_modules', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'gulpfile.js', 'README.md']
